CREATE DATABASE portfolio;

USE portfolio; 

CREATE TABLE port_itens(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,	
titulo VARCHAR(64) NOT NULL,
descricao TEXT NOT NULL,
tecnologias VARCHAR(256) NOT NULL,
imgCaminho VARCHAR(256) NOT NULL,
link VARCHAR(256) NOT NULL
);

